---
- name: Configuration de l'AMI Ubuntu
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Activer le dépôt Universe
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal universe
        update_cache: yes

    - name: Créer un utilisateur sécurisé
      user:
        name: secure_user
        shell: /bin/bash

    - name: Activer la journalisation des connexions SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?LogLevel'
        line: 'LogLevel VERBOSE'

    - name: Installer Auditd pour surveiller les accès root
      apt:
        name: auditd
        state: present

    - name: Mise à jour des paquets (avec retry)
      apt:
        update_cache: yes
      register: apt_update
      until: apt_update is succeeded
      retries: 3
      delay: 15

    - name: Installer Fail2ban
      apt:
        name: fail2ban
        state: latest

    - name: Mise à jour complète du système
      apt:
        upgrade: dist
        update_cache: yes

    - name: Sécuriser la configuration SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
        validate: /usr/sbin/sshd -T -f %s
      loop:
        - { regex: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
        - { regex: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
      notify:
        - Redémarrer SSH

    - name: Nettoyage des paquets
      apt:
        autoremove: yes
        autoclean: yes

  handlers:
    - name: Redémarrer SSH
      service:
        name: sshd
        state: restarted
