---
- name: Configuration de l'instance Ubuntu
  hosts: all
  become: yes
  vars:
    fail2ban_config:
      - regex: PermitRootLogin yes
        replace: PermitRootLogin no

  tasks:
    - name: Ajout du dépôt Universe
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal universe
        update_cache: yes

    - name: Mise à jour du cache apt (avec retry)
      apt:
        update_cache: yes
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: Installation de fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Mise à jour complète du système
      apt:
        upgrade: dist
        update_cache: yes

    - name: Configuration SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regex }}"
        line: "{{ item.replace }}"
        validate: /usr/sbin/sshd -T -f %s
      loop: "{{ fail2ban_config }}"
      notify:
        - Restart SSH

    - name: Nettoyage des paquets
      apt:
        autoremove: yes
        autoclean: yes

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
