name: Build and Test AMI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

         # Étape 2 : Créer le fichier de clé privée
      - name: Create SSH private key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/packer_key.pem
          chmod 600 ~/.ssh/packer_key.pem

      # Étape 2 : Installer Packer
      - name: Install Packer
        uses: hashicorp/setup-packer@v2

         # Étape 2 : Configurer les credentials AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Étape 3 : Initialiser les plugins Packer
      - name: Initialize Packer plugins
        run: packer init template.pkr.hcl

      # Étape 4 : Valider le template Packer
      - name: Validate Packer template
        run: packer validate template.pkr.hcl

      # Étape 5 : Construire l'AMI avec Packer
      - name: Build AMI with Packer
        run: packer build template.pkr.hcl
